apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
