---
# This role assumes to call Kubespray's `playbooks/cluster`.
- name: Install Kubernetes
  ansible.builtin.import_playbook: playbooks/cluster.yml

- name: Registernqualified
  hosts: all
  tasks:
    - ansible.builtin.file:
        path: /etc/containers/registries.conf.d
        state: directory
        mode: '0755'
    - ansible.builtin.copy:
        dest: /etc/containers/registries.conf.d/01-unqualified.conf
        content: |

          unqualified-search-registries = ['docker.io', 'quay.io']

- name: Download amind.conf to localhost
  hosts: kube_control_plane
  run_once: true
  tasks:
    - ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/admin.conf
        flat: yes
    - delegate_to: localhost
      ansible.builtin.replace:
        path: ~/.kube/admin.conf
        regexp: '127.0.0.1'
        replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
