apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno
rendezvousIP: 192.168.8.80
hosts:
  - hostname: master0
    interfaces:
      - name: ens3
        macAddress: 52:54:00:00:00:50
    rootDeviceHints:
      deviceName: "/dev/vda"
    networkConfig:
      interfaces:
        - name: ens3
          type: ethernet
          state: up
          mac-address: 52:54:00:00:00:50
          ipv4:
            enabled: true
            address:
              - ip: 192.168.8.80
                prefix-length: 24 
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.8.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.8.1 
            next-hop-interface: ens3
            table-id: 254

